<<<<<<< HEAD
# Generated by Django 4.1 on 2022-08-16 17:12
=======
# Generated by Django 4.1 on 2022-08-18 14:45
>>>>>>> 02028ec6821a5dfea096304e41e29bcb223d33cd

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='otData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno', models.IntegerField()),
                ('dataStream', models.CharField(max_length=255)),
=======
            name='otModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno1', models.IntegerField()),
                ('dataStream', models.CharField(max_length=30)),
>>>>>>> 02028ec6821a5dfea096304e41e29bcb223d33cd
            ],
        ),
    ]
