# Generated by Django 4.1 on 2022-08-18 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='otModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sno1', models.IntegerField()),
                ('dataStream', models.CharField(max_length=30)),
            ],
        ),
    ]
